backend:
  name: github
  repo: nathanforce/negarmorshediantherapy.com

media_folder: static/assets

collections:
  - name: about
    label: about
    folder: content
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: text, label: Text }

  - name: couples_and_family_therapy
    label: couples_and_family_therapy
    folder: content
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: text, label: Text }