backend:
  name: github
  repo: nathanforce/negarmorshediantherapy.com

media_folder: static/assets

- label: "Pages"
  name: "pages"
  files:
    - label: "About Page"
      name: "about"
      file: "content/about.md"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Content, name: content, widget: markdown}