backend:
  name: github
  repo: nathanforce/negarmorshediantherapy.com

media_folder: static/assets

collections:
  - label: "Pages"
    name: "pages"
    files:
      - name: about
        label: About
        file: content/about.md
        fields:
          - { name: title, label: Title }
          - { name: text, label: Text, widget: 'markdown' }

      - name: couples_and_family_therapy
        label: Couple and Family Therapy
        file: content/couples_and_family_therapy.md
        fields:
          - { name: title, label: Title }
          - { name: text, label: Text, widget: 'markdown' }
