backend:
  name: github
  repo: nathanforce/negarmorshediantherapy.com

media_folder: static/assets

collections:
  - name: about
    label: about
    file: content/about.md
    fields:
      - { name: title, label: Title }
      - { name: text, label: Text, widget: 'markdown' }

  - name: couples_and_family_therapy
    label: couples_and_family_therapy
    file: content/couples_and_family_therapy.md
    fields:
      - { name: title, label: Title }
      - { name: text, label: Text, widget: 'markdown' }